### ISSUE TITLE
Variablen-Name nicht aussagekräftig

### ISSUE THREAD

**Issue by Kaes3kuch3n** [FH-Technikum-Wien/MazeAlgorithm#1]
https://github.com/FH-Technikum-Wien/MazeAlgorithm/blob/f793c6c5409b64027a8d82f0eda33c5597ddfee3/MazeAlgorithm.cpp#L29

Siehe verlinkte Zeile. f ist nicht sehr aussagekräftig. Bitte ändern.

**Comment by DavidPgl** [comment]
"f" ist eine häufig verwendete Bezeichnung einer Variablen des A* Algorithmus. Kommentare zur Verdeutlichung hinzugefügt:P
